# ARTS configuration

# general config for all science cases
# also loaded when reading SC3 or SC4 config
general: &general
    # nr of bits per sample
    nbit: 8
    # total nr of channels
    nchan: 1536
    # fine channels per channel
    nchan_fine: 16
    # minimum frequency (center of lowest subband)
    freq_low: 1200
    # first subband (usually 64, corresponding to 50 MHz)
    first_subband: 64
    # bandwidth
    bw: 300
    # seconds to timestamp conversion
    time_unit: 781250
    # total nr of beams
    nbeams: 40
    # beams that are not present
    missing_beams: []
    # nr of buffers for readers
    nbuffer: 5
    # size of ringbuffer header
    hdr_size: 40960
    # observation modes
    valid_modes: [scrub, dump, fil, fits, amber, survey, record]
    # network port of CB00 for I
    network_port_start: 5000
    # network port of CB00 for IQUV
    iquv_network_port_start: 6000
    # output directory of stokes I data
    output_dir: "/data2/output/{date}/{datetimesource}"
    # output directory of amber triggers
    amber_dir: "/data2/output/{date}/{datetimesource}/amber"
    # log prefix
    log_dir: "{home}/observations/log/{date}/{datetimesource}"
    # master output dir
    master_dir: "{home}/observations/results/{date}/{datetimesource}"
    # output dir of IQUV dumps
    iquv_output_dir: "/data1/output/{date}/{datetimesource}/iquv"
    # output of everything in debug mode
    debug_dir : "{home}/debug"
    # fits templates dir
    fits_templates: "{home}/software/dadafits/templates"
    # dada event port for I
    dada_event_port_i: 30000
    # dada event port for IQUV
    dada_event_port_iquv: 30001

# Science case 3
sc3:
    <<: *general
    # sampling time
    tsamp: 81.92E-6
    # ringbuffer page size, is nr of samples per 1.024s
    page_size: 12500

# Science case 4
sc4:
    <<: *general
    # sampling time
    tsamp: 81.92E-6
    # ringbuffer page size, is nr of samples per 1.024s
    page_size: 12500

# Stokes I + Tied Array Beam
i+tab:
    # number of tied-array beams
    ntabs: 12
    # number of synthesized beams
    nsynbeams: 12
    # dadafilterbank mode
    science_mode: 0

# Stokes IQUV + Tied Array Beam
iquv+tab:
    # number of tied-array beams
    ntabs: 12
    # dadafilterbank mode
    science_mode: 1

# Stokes I + Incoherent Array Beam
i+iab:
    # number of tied-array beams
    ntabs: 1
    # number of synthesized beams
    nsynbeams: 1
    # dadafilterbank mode
    science_mode: 2
    
# Stokes IQUV + Incoherent Array Beam
iquv+iab:
    # number of tied-array beams
    ntabs: 1
    # dadafilterbank mode
    science_mode: 3

# core affinities
# the HDDs and GPU 0,1 are on NUMA node 0 = cpu 0-9,20-29
# the 40Gbit link and GPU 2,3 are on NUMA node 1 = cpu 10-19,30-39
affinity:
    fill_ringbuffer_i: 11
    fill_ringbuffer_iquv: 12
    dada_db_i: 13
    dada_db_i_event: 17
    dada_db_iquv: 14
    dada_db_iquv_event: 18
    dadafilterbank: 1
    dadafits: 2
    dada_dbdisk_i: 3
    dada_dbdisk_iquv: 4
    # note: one cpu for each AMBER instance, corresponding to GPU 1,2,3
    amber: [3, 15, 16]

# Emailer settings
emailer:
    to: [arts-alerts@astron.nl]
